import type { Task, Goal, GardenProgress, FocusSession, AIRecommendation, ProgressLog } from '@/types/database'

// ─── Mock Tasks ────────────────────────────────────────────────────────────────
export const mockTasks: Task[] = [
  {
    id: 't1',
    user_id: 'u1',
    title: 'Finalize project presentation',
    description: 'Complete slides and rehearse for the client meeting',
    status: 'in_progress',
    priority: 'critical',
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimated_minutes: 180,
    tags: ['work', 'presentation'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't2',
    user_id: 'u1',
    title: 'Update portfolio website',
    description: 'Add recent projects and update skills section',
    status: 'todo',
    priority: 'high',
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    estimated_minutes: 240,
    tags: ['portfolio', 'career'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't3',
    user_id: 'u1',
    title: 'Review pull requests',
    description: 'Code review for team members\' PRs',
    status: 'todo',
    priority: 'medium',
    due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimated_minutes: 60,
    tags: ['dev', 'team'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't4',
    user_id: 'u1',
    title: 'Morning exercise routine',
    description: '30 min cardio + stretching',
    status: 'completed',
    priority: 'medium',
    estimated_minutes: 45,
    tags: ['health', 'daily'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't5',
    user_id: 'u1',
    title: 'Write blog post draft',
    description: 'Draft post on AI productivity tools',
    status: 'todo',
    priority: 'low',
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    estimated_minutes: 120,
    tags: ['writing', 'content'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't6',
    user_id: 'u1',
    title: 'Complete online course module',
    description: 'React advanced patterns — Module 3',
    status: 'in_progress',
    priority: 'high',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    estimated_minutes: 90,
    tags: ['learning', 'react'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// ─── Mock Goals ────────────────────────────────────────────────────────────────
export const mockGoals: Goal[] = [
  {
    id: 'g1',
    user_id: 'u1',
    title: 'Land a Software Engineering Internship',
    description: 'Secure a summer 2025 SWE internship at a top tech company',
    category: 'career',
    status: 'active',
    target_date: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    progress_percent: 45,
    ai_generated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'g2',
    user_id: 'u1',
    title: 'Launch Personal SaaS Product',
    description: 'Build and ship a micro-SaaS app with 10 paying customers',
    category: 'project',
    status: 'active',
    target_date: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    progress_percent: 28,
    ai_generated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'g3',
    user_id: 'u1',
    title: 'Read 12 Books This Year',
    description: 'One book per month — mix of technical and personal growth',
    category: 'personal',
    status: 'active',
    target_date: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
    progress_percent: 58,
    ai_generated: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// ─── Mock Garden ───────────────────────────────────────────────────────────────
export const mockGarden: GardenProgress = {
  id: 'gp1',
  user_id: 'u1',
  total_plants: 14,
  current_streak: 5,
  longest_streak: 12,
  total_tasks_completed: 47,
  level: 3,
  xp: 470,
  garden_items: [
    { id: 'gi1', type: 'tree', emoji: '🌳', name: 'Oak of Completion', earned_at: new Date().toISOString(), position: { x: 15, y: 60 } },
    { id: 'gi2', type: 'tree', emoji: '🌲', name: 'Pine of Persistence', earned_at: new Date().toISOString(), position: { x: 75, y: 55 } },
    { id: 'gi3', type: 'bush', emoji: '🌿', name: 'Focus Fern', earned_at: new Date().toISOString(), position: { x: 35, y: 70 } },
    { id: 'gi4', type: 'bush', emoji: '🪴', name: 'Goal Plant', earned_at: new Date().toISOString(), position: { x: 55, y: 72 } },
    { id: 'gi5', type: 'plant', emoji: '🌻', name: 'Sunflower Sprint', earned_at: new Date().toISOString(), position: { x: 25, y: 74 } },
    { id: 'gi6', type: 'plant', emoji: '🌺', name: 'Achievement Bloom', earned_at: new Date().toISOString(), position: { x: 65, y: 74 } },
    { id: 'gi7', type: 'plant', emoji: '🌸', name: 'Cherry Blossom', earned_at: new Date().toISOString(), position: { x: 45, y: 76 } },
    { id: 'gi8', type: 'sprout', emoji: '🌱', name: 'New Habit Sprout', earned_at: new Date().toISOString(), position: { x: 20, y: 80 } },
    { id: 'gi9', type: 'sprout', emoji: '🌱', name: 'Growing Sprout', earned_at: new Date().toISOString(), position: { x: 80, y: 78 } },
    { id: 'gi10', type: 'sprout', emoji: '🌱', name: 'Focus Sprout', earned_at: new Date().toISOString(), position: { x: 60, y: 80 } },
  ],
  updated_at: new Date().toISOString(),
}

// ─── Mock Focus Sessions ───────────────────────────────────────────────────────
export const mockFocusSessions: FocusSession[] = [
  {
    id: 'fs1',
    user_id: 'u1',
    mode: 'pomodoro',
    planned_duration_minutes: 25,
    actual_duration_minutes: 25,
    status: 'completed',
    started_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    ended_at: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'fs2',
    user_id: 'u1',
    mode: 'deep_work',
    planned_duration_minutes: 90,
    actual_duration_minutes: 87,
    status: 'completed',
    started_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    ended_at: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
  },
]

// ─── Mock AI Recommendations ───────────────────────────────────────────────────
export const mockRecommendations: AIRecommendation[] = [
  {
    id: 'r1',
    user_id: 'u1',
    type: 'deadline_warning',
    title: '⚠️ Presentation deadline approaching fast',
    content: 'Your client presentation is in 2 days. Based on your current progress, you\'re at moderate risk of missing quality targets.',
    action_items: [
      'Block 3 hours tomorrow morning for slide completion',
      'Schedule a practice run with a friend or teammate',
      'Prepare backup slides for Q&A',
    ],
    priority: 'high',
    dismissed: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'r2',
    user_id: 'u1',
    type: 'break_suggestion',
    title: '☕ Take a mindful break',
    content: 'You\'ve been focused for 2 hours. A 10-minute break will boost your productivity for the next session.',
    action_items: ['Step outside for fresh air', 'Do 5 minutes of stretching', 'Drink a glass of water'],
    priority: 'low',
    dismissed: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'r3',
    user_id: 'u1',
    type: 'goal_insight',
    title: '🎯 Internship goal on track!',
    content: 'Great progress on your internship goal. Your portfolio update will significantly boost your application strength.',
    action_items: [
      'Add your recent React project to portfolio',
      'Apply to 3 companies this week',
      'Reach out to 2 contacts on LinkedIn',
    ],
    priority: 'medium',
    dismissed: false,
    created_at: new Date().toISOString(),
  },
]

// ─── Mock Progress Logs ────────────────────────────────────────────────────────
export const mockProgressLogs: ProgressLog[] = Array.from({ length: 14 }, (_, i) => ({
  id: `pl${i}`,
  user_id: 'u1',
  date: new Date(Date.now() - i * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  tasks_completed: Math.floor(Math.random() * 8) + 1,
  focus_minutes: Math.floor(Math.random() * 180) + 30,
  mood_score: Math.floor(Math.random() * 5) + 1,
  created_at: new Date(Date.now() - i * 24 * 60 * 60 * 1000).toISOString(),
}))

// ─── Dashboard Stats ───────────────────────────────────────────────────────────
export const mockDashboardStats = {
  todayTasksCompleted: 3,
  todayTasksTotal: 7,
  weekFocusMinutes: 847,
  currentStreak: 5,
  weeklyGoalProgress: 68,
  riskScore: 42,
  plantsGrown: 14,
}
